apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: your-registry/chat-service:latest
          ports:
            - containerPort: 50052
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/chat_db
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
